# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 309)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputField = QtWidgets.QTextEdit(self.centralwidget)
        self.InputField.setGeometry(QtCore.QRect(20, 40, 201, 251))
        self.InputField.setObjectName("InputField")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(11)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ChooseWorkType = QtWidgets.QComboBox(self.centralwidget)
        self.ChooseWorkType.setGeometry(QtCore.QRect(480, 140, 121, 24))
        self.ChooseWorkType.setEditable(False)
        self.ChooseWorkType.setMaxVisibleItems(10)
        self.ChooseWorkType.setDuplicatesEnabled(False)
        self.ChooseWorkType.setObjectName("ChooseWorkType")
        self.ChooseWorkType.addItem("")
        self.ChooseWorkType.addItem("")
        self.OutputField = QtWidgets.QTextEdit(self.centralwidget)
        self.OutputField.setGeometry(QtCore.QRect(250, 40, 201, 251))
        self.OutputField.setReadOnly(True)
        self.OutputField.setObjectName("OutputField")
        self.KeyField = QtWidgets.QTextEdit(self.centralwidget)
        self.KeyField.setGeometry(QtCore.QRect(470, 60, 261, 31))
        self.KeyField.setObjectName("KeyField")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(539, 200, 131, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 10, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 30, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 110, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(11)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.AESTypeBox = QtWidgets.QComboBox(self.centralwidget)
        self.AESTypeBox.setGeometry(QtCore.QRect(620, 140, 101, 24))
        self.AESTypeBox.setObjectName("AESTypeBox")
        self.AESTypeBox.addItem("")
        self.AESTypeBox.addItem("")
        self.AESTypeBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 110, 101, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab №3 - AES"))
        self.label.setText(_translate("MainWindow", "Поле Ввода"))
        self.ChooseWorkType.setCurrentText(_translate("MainWindow", "Шифрование"))
        self.ChooseWorkType.setItemText(0, _translate("MainWindow", "Шифрование"))
        self.ChooseWorkType.setItemText(1, _translate("MainWindow", "Дешифрование"))
        self.pushButton.setText(_translate("MainWindow", "Выполнить"))
        self.label_2.setText(_translate("MainWindow", "Результат "))
        self.label_3.setText(_translate("MainWindow", "Ключ"))
        self.label_4.setText(_translate("MainWindow", "Тип работы"))
        self.AESTypeBox.setItemText(0, _translate("MainWindow", "AES-128"))
        self.AESTypeBox.setItemText(1, _translate("MainWindow", "AES-192"))
        self.AESTypeBox.setItemText(2, _translate("MainWindow", "AES-256"))
        self.label_5.setText(_translate("MainWindow", "Вид алгоритма"))
