# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 503)
        MainWindow.setMinimumSize(QtCore.QSize(800, 503))
        MainWindow.setMaximumSize(QtCore.QSize(800, 503))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.encodeButton.setGeometry(QtCore.QRect(640, 60, 121, 28))
        self.encodeButton.setObjectName("encodeButton")
        self.inputField = QtWidgets.QTextEdit(self.centralwidget)
        self.inputField.setGeometry(QtCore.QRect(40, 50, 291, 181))
        self.inputField.setObjectName("inputField")
        self.pField = QtWidgets.QTextEdit(self.centralwidget)
        self.pField.setGeometry(QtCore.QRect(380, 50, 201, 31))
        self.pField.setObjectName("pField")
        self.gField = QtWidgets.QTextEdit(self.centralwidget)
        self.gField.setGeometry(QtCore.QRect(380, 100, 201, 31))
        self.gField.setObjectName("gField")
        self.xField = QtWidgets.QTextEdit(self.centralwidget)
        self.xField.setGeometry(QtCore.QRect(380, 210, 201, 31))
        self.xField.setObjectName("xField")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 30, 151, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.encodeField = QtWidgets.QTextEdit(self.centralwidget)
        self.encodeField.setGeometry(QtCore.QRect(40, 290, 331, 181))
        self.encodeField.setReadOnly(True)
        self.encodeField.setObjectName("encodeField")
        self.decodeField = QtWidgets.QTextEdit(self.centralwidget)
        self.decodeField.setGeometry(QtCore.QRect(440, 290, 321, 181))
        self.decodeField.setReadOnly(True)
        self.decodeField.setObjectName("decodeField")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 161, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 250, 161, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 190, 151, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 250, 161, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.yField = QtWidgets.QTextEdit(self.centralwidget)
        self.yField.setGeometry(QtCore.QRect(380, 150, 201, 31))
        self.yField.setObjectName("yField")
        self.decodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.decodeButton.setGeometry(QtCore.QRect(640, 90, 121, 28))
        self.decodeButton.setObjectName("decodeButton")
        self.keysButton = QtWidgets.QPushButton(self.centralwidget)
        self.keysButton.setGeometry(QtCore.QRect(610, 200, 181, 41))
        self.keysButton.setIconSize(QtCore.QSize(16, 16))
        self.keysButton.setObjectName("keysButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 50, 31, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(350, 100, 31, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(350, 150, 31, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(350, 210, 31, 31))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab№4 - Elgamal cypher"))
        self.encodeButton.setText(_translate("MainWindow", "Шифровать"))
        self.label.setText(_translate("MainWindow", "Открытый ключ"))
        self.label_2.setText(_translate("MainWindow", "Исходные данные"))
        self.label_3.setText(_translate("MainWindow", "Зашифрованные данные"))
        self.label_4.setText(_translate("MainWindow", "Закрытый ключ"))
        self.label_5.setText(_translate("MainWindow", "Дешифрованные данные"))
        self.decodeButton.setText(_translate("MainWindow", "Расшифровать"))
        self.keysButton.setText(_translate("MainWindow", "Сгенерировать ключи"))
        self.label_6.setText(_translate("MainWindow", "p ="))
        self.label_7.setText(_translate("MainWindow", "g ="))
        self.label_8.setText(_translate("MainWindow", "y ="))
        self.label_9.setText(_translate("MainWindow", "x ="))
